# Generated by Django 4.2.3 on 2023-09-26 19:58

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import giftweb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('body', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('read_more', models.CharField(default='GiftCard', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('countdown_time', models.DurationField()),
                ('image', cloudinary.models.CloudinaryField(default='https://cdn1.iconfinder.com/data/icons/technology-devices-2/100/Profile-512.png', max_length=255, verbose_name='image')),
                ('extra_feature', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tracking_id', models.CharField(default='nil', max_length=255)),
                ('current_location', models.CharField(default='nil', max_length=255)),
                ('quantity', models.CharField(default='nil', max_length=255)),
                ('brand', models.CharField(default='nil', max_length=255)),
                ('sub_category', models.CharField(default='nil', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('UNAVAILABLE', 'UNAVAILABLE')], default='ACTIVE', max_length=17)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('countdown_time', models.DurationField()),
                ('image', cloudinary.models.CloudinaryField(default='https://cdn1.iconfinder.com/data/icons/technology-devices-2/100/Profile-512.png', max_length=255, verbose_name='image')),
                ('image2', cloudinary.models.CloudinaryField(default='https://cdn1.iconfinder.com/data/icons/technology-devices-2/100/Profile-512.png', max_length=255, verbose_name='image')),
                ('image3', cloudinary.models.CloudinaryField(default='https://cdn1.iconfinder.com/data/icons/technology-devices-2/100/Profile-512.png', max_length=255, verbose_name='image')),
                ('image4', cloudinary.models.CloudinaryField(default='https://cdn1.iconfinder.com/data/icons/technology-devices-2/100/Profile-512.png', max_length=255, verbose_name='image')),
                ('image5', cloudinary.models.CloudinaryField(default='https://cdn1.iconfinder.com/data/icons/technology-devices-2/100/Profile-512.png', max_length=255, verbose_name='image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='giftweb.category')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=100)),
                ('payment_id', models.CharField(blank=True, default=giftweb.models.generate_tracking_id, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('country', models.CharField(default='nil', max_length=255)),
                ('full_name', models.CharField(default='nil', max_length=255)),
                ('street_address', models.CharField(default='nil', max_length=200)),
                ('apartment_address', models.CharField(default='nil', max_length=200)),
                ('phone_number', models.CharField(default='nil', max_length=200)),
                ('proof_of_pay', cloudinary.models.CloudinaryField(default='https://cdn1.iconfinder.com/data/icons/technology-devices-2/100/Profile-512.png', max_length=255, verbose_name='image')),
                ('gift_card_type', models.CharField(choices=[('apple', 'Apple Card'), ('amazon', 'Amazon Card'), ('steam', 'Steam Card'), ('xbox', 'Xbox Card')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete')], default='PENDING', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('premium_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftweb.premiumproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftweb.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftweb', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manage Deposit/Payment',
                'verbose_name_plural': 'Manage Deposit/Payment',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('premium_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftweb.premiumproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftweb.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
